name: Deploy to GitHub Pages

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - name: Install dependencies
      run: npm ci

    - name: Set author email
      run: git config user.email "davykamanzi@gmail.com"
    
    - name: Set author name
      run: git config user.name "Davy Kamanzi"

    - name: Generate production build
      run: npm run deploy
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
